modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Creative Commons Liscence"

[[mods]]
modId = "piemod"
version = "${version}"
displayName = "The Pie Mod"
authors = "ILIKEPIEFOO2"
description = '''
Welcome to the Pie Mod!
'''
#logoFile = ""

[[dependencies.piemod]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.piemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.piemod]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"